mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

spring:
  servlet:
    multipart:
      max-file-size: 1500MB
      max-request-size: 1500MB

  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: LKCzka2233
    driver-class-name: com.mysql.cj.jdbc.Driver

  security:
    oauth2:
      authorizationserver:
        client:
          pixiv:
            registration:
              client-id: "pixiv"
              client-secret: "123456"
              client-authentication-methods:
                - "client_secret_basic"
              authorization-grant-types:
                - "authorization_code"
                - "refresh_token"
              redirect-uris:
                - "http://127.0.0.1:8080/pixiv/webjars/oauth/oauth2.html"
              post-logout-redirect-uris:
                - "http://127.0.0.1:8080/pixiv"
              scopes:
                - "openid"
                - "profile"
                - "read"
                - "write"
              require-authorization-consent: true

server:
  servlet:
    context-path: /pixiv
  address: 127.0.0.1

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    persist-authorization: true

knife4j:
  enable: true
  setting:
    language: zh_cn

logging:
  level:
    org.springframework.security: trace



