mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

spring:
  servlet:
    multipart:
      max-file-size: 1500MB
      max-request-size: 1500MB

  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0

  datasource:
    url:  jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: LKCzka2233
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  servlet:
    context-path: /pixiv